WIP: Feat/545/quick filters
SAP/guided-answers-extension pull request #547
Opened 2023-07-27 14:08 UTC by oliversberzs

# Issue

#545

## Description

* Added quick filters section to home page

2023-07-31 19:09 UTC, Klaus-Keller requested changes
See my comments

2023-07-31 19:09 UTC, Klaus-Keller commented on packages/ide-extension/src/panel/guidedAnswersPanel.ts
> +        await this.loadQuickFilters(this.ide);
If Guided Answers extension is started with arguments (`this.startOptions`) to load a certain tree and node path, I think we should show what was passed as argument and NOT overwrite it with quickfilters. That is why it previously was in the `else`-branch.

2023-08-01 07:38 UTC, oliversberzs commented on packages/core/test/guided-answers-api.test.ts
> +        expect(options.logger?.logString).toBeCalledWith(expect.stringContaining('Error when parsing argument'));
I noticed that the error that the JSON parsing throws is has a different message on different node versions, so it is a lot safer and consistent to test not for the error message that node throws, but the specific one we are throwing
![image](https://github.com/SAP/guided-answers-extension/assets/105420446/87b4bf88-ef7b-4b7d-878b-55b524025789)

2023-08-02 20:25 UTC, Klaus-Keller commented on packages/ide-extension/src/panel/guidedAnswersPanel.ts
> +        await this.loadQuickFilters(this.ide);
Great find, and also a good reminder that we need to extend the node versions for pipeline builds. Currently only 
```
node-version: [16.x, 18.x]
```
https://github.com/SAP/guided-answers-extension/blob/5af480cd96bf64e31bc3cc139906630ecc515bb4/.github/workflows/pipeline.yml#L14C20-L14C20

I'll create a separate PR for this.

2023-08-02 20:26 UTC, Klaus-Keller commented on packages/core/test/guided-answers-api.test.ts
> +        expect(options.logger?.logString).toBeCalledWith(expect.stringContaining('Error when parsing argument'));
Great find, and also a good reminder that we need to extend the node versions for pipeline builds. Currently only 
```
node-version: [16.x, 18.x]
```
https://github.com/SAP/guided-answers-extension/blob/5af480cd96bf64e31bc3cc139906630ecc515bb4/.github/workflows/pipeline.yml#L14C20-L14C20

I'll create a separate PR for this.

2023-08-02 20:37 UTC, Klaus-Keller commented on packages/ide-extension/src/panel/guidedAnswersPanel.ts
> +        await this.loadQuickFilters(this.ide);
Sorry, I missed the part that behavior of quick filters slightly changed, they are not loaded on start anymore. Saw that now in the ticket.

2023-08-02 20:38 UTC, Klaus-Keller approved these changes
- code changes look good
- test coverage is good
- tested locally, but not on SBAS

Approved from my side.

2023-08-03 09:35 UTC, merged

2023-08-03 09:47 UTC, unseen1980 commented on packages/webapp/src/webview/ui/components/QuickFilters/QuickFilters.tsx
> +                <span style={{ margin: '0 5px' }}>Quick Filters</span>
@oliversberzs Can you please in one of your next PRs update here the text with i18n values? Thanks
https://github.com/SAP/guided-answers-extension/blob/main/packages/webapp/src/webview/i18n/i18n.json